name: Test and Build container

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      
      - name: Build 
        run: |
          docker build -t base_container --target base .
          docker build -t rust_container .
